all: bem_vindo diario adeus

bem_vindo:
  @echo "Oi! Que tal me contar como foi o seu dia?"
  
diario:
  @echo "Depois de escrever pressione "ctrl + d""
  @cat > diario.txt

adeus:
  g++ -o tchau tchau.c
  @./tchau